make todone error if no tasks match the given pattern

diff --git a/todone b/todone
--- a/todone
+++ b/todone
@@ -14,8 +14,10 @@ fi
 
 touch "$TODO_F.tmp"
 
+HAD_MATCH=0
 while read -r LINE; do
   if [ "${LINE#TODO *$PAT}" != "$LINE" ]; then
+    HAD_MATCH=1
     TASK="${LINE#TODO }"
     printf "• $BEGIN_DONE%s$END_DONE\n" "$TASK"
     LINE=$(printf "DONE %s ($(date "+%Y-%m-%d %R"))" "$TASK")
@@ -23,5 +25,10 @@ while read -r LINE; do
   fi
   printf "%s\n" "$LINE" >> "$TODO_F.tmp"
 done < "$TODO_F"
+
+if [ $HAD_MATCH -eq 0 ]; then
+  printf "Error: no tasks matched the given pattern\n" >&2
+  exit 1
+fi
 
 mv "$TODO_F.tmp" "$TODO_F"
